### ISSUE TITLE
How to test changes to buildbot?

### ISSUE THREAD

**Issue by Moxinilian** [llvm/llvm-zorg#160]
I am trying to add a reporter to the buildbot configuration so a comment tagging the authors is created on a commit for which a build has failed. However, this is my first time touching buildbot configs and while I am slowly starting to understand how buildbot works, I have no idea how to actually test my code.

Is this even possible? If not, how does one create changes? @gkistanova maybe you would know?

**Comment by DavidSpickett** [comment]
Recent changes by @asb have addressed this. Start with https://llvm.org/docs/HowToAddABuilder.html#testing-a-builder-config-locally. If you want to change Buildbot itself, you could get the source of the version listed there and modify it.

For the basic stuff like syntax, Alex has also enabled CI on this repo to check that - https://github.com/llvm/llvm-zorg/pull/303.
