### ISSUE TITLE
sanitizer-buildbot-android is missing python or misconfigured

### ISSUE THREAD

**Issue by jayfoad** [llvm/llvm-zorg#218]
I got this email from buildbot:
```
BUILD FAILED: failed 'python ../sanitizer_buildbot/sanitizers/zorg/buildbot/builders/sanitizers/buildbot_selector.py' (failure)

Step 2 (annotate) failure: 'python ../sanitizer_buildbot/sanitizers/zorg/buildbot/builders/sanitizers/buildbot_selector.py' (failure)
Upon execvpe b'python' [b'python', b'../sanitizer_buildbot/sanitizers/zorg/buildbot/builders/sanitizers/buildbot_selector.py'] in environment id 140401582393280
:Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/twisted/internet/process.py", line 397, in _fork
    self._execChild(path, uid, gid, executable, args, environment)
  File "/usr/lib/python3/dist-packages/twisted/internet/process.py", line 468, in _execChild
    os.execvpe(executable, args, environment)
  File "/usr/lib/python3.10/os.py", line 584, in execvpe
    _execvpe(file, args, env)
  File "/usr/lib/python3.10/os.py", line 617, in _execvpe
    raise last_exc
  File "/usr/lib/python3.10/os.py", line 608, in _execvpe
    exec_func(fullname, *argrest)
FileNotFoundError: [Errno 2] No such file or directory: b'/snap/bin/python'
```
From the last line it seems pretty clear that this is a configuration problem with the build machine. How can I easily report problems like this one to whoever is responsible for maintaining the appropriate build?

**Comment by gkistanova** [comment]
Thanks for reporting this, Jay!

Could you provide a direct link to the build in question, please? Or forward me the email in question.

In general, you would check the worker the build failed on. The owner of that worker is the right contact to report the issue to. Every worker has an owner. For example, if you look at https://lab.llvm.org/buildbot/#/workers/136 you see that I own that worker (check the field "Admin" in the worker information).

You can either send a direct email to the owner, or create an issue here and assign it to the owner.

**Comment by gkistanova** [comment]
Here is the direct link to one of the failing builds:
https://lab.llvm.org/buildbot/#/builders/186/builds/210/steps/2/logs/stdio

@vitalybuka Vitaly, could you take a look, please?

**Comment by vitalybuka** [comment]
Sorry, it was an intermittent issue after the bot upgrade, already fixed.

**Comment by vitalybuka** [comment]
Fixed.

Sorry for that. I've should switch it to staging for distrib upgrade.

**Comment by jayfoad** [comment]
> Could you provide a direct link to the build in question, please? Or forward me the email in question.

Sorry, I omitted the start of the email:
```
The Buildbot has detected a new failure on builder sanitizer-x86_64-linux-android while building llvm.

Full details are available at:
    https://lab.llvm.org/buildbot/#/builders/186/builds/198
```
Thanks for the fix.
